### ISSUE TITLE
problem when i try to run it 

### ISSUE THREAD

**Issue by opsaw** [maldevel/IPGeoLocation#18]
problem when i try to run it 

Traceback (most recent call last):
  File "./ipgeolocation.py", line 32, in <module>
    from core.IpGeoLocationLib import IpGeoLocationLib
  File "/root/Desktop/IPGeoLocation/core/IpGeoLocationLib.py", line 30, in <module>
    from core.Utils import Utils
  File "/root/Desktop/IPGeoLocation/core/Utils.py", line 35, in <module>
    from core.Logger import Logger
  File "/root/Desktop/IPGeoLocation/core/Logger.py", line 32, in <module>
    from termcolor import colored
ImportError: No module named 'termcolor'

help please !

**Comment by maldevel** [comment]
pip install -r requirements.txt --user

**Comment by opsaw** [comment]
Requirement already satisfied (use --upgrade to upgrade): termcolor in /usr/lib/python2.7/dist-packages (from -r requirements.txt (line 1))
Requirement already satisfied (use --upgrade to upgrade): colorama in /usr/lib/python2.7/dist-packages (from -r requirements.txt (line 2))
Cleaning up...

**Comment by maldevel** [comment]
you need Python 3 please read Readme file
