### ISSUE TITLE
No module Named Termcolor

### ISSUE THREAD

**Issue by XSecr3t** [maldevel/IPGeoLocation#20]
Hello

I already install requirements and found that Termcolor and colorama already satisfied on my termux but why when i run 

python3 ipgeolocation.py -m or anything that i was want run always having error 

> root@Mr.XSecr3t:~#python3 ipgeolocation.py -m
WARNING: linker: Unsupported flags DT_FLAGS_1=0x8
WARNING: linker: Unsupported flags DT_FLAGS_1=0x8
Traceback (most recent call last):
  File "ipgeolocation.py", line 32, in <module>
    from core.IpGeoLocationLib import IpGeoLocationLib
  File "/data/data/com.termux/files/home/IPGeoLocation/core/IpGeoLocationLib.py", line 30, in <module>
    from core.Utils import Utils
  File "/data/data/com.termux/files/home/IPGeoLocation/core/Utils.py", line 35, in <module>
    from core.Logger import Logger
  File "/data/data/com.termux/files/home/IPGeoLocation/core/Logger.py", line 32, in <module>
    from termcolor import colored
ModuleNotFoundError: No module named 'termcolor'
root@Mr.XSecr3t:~#

Is there anything wrong with this step?
Help please.

**Comment by E33odd** [comment]
Same issue here.. 🤔😑😐😐😐😐

**Comment by 21Howitzer** [comment]
pip install termcolor

**Comment by GrimReaperRioxZ** [comment]
fix this is please. i want run the ipgeolocation but like this
    ↓
Traceback (most recent call last):
  File "ipgeolocation.py", line 32, in <module>
    from core.IpGeoLocationLib import IpGeoLocationLib
  File "/data/data/com.termux/files/home/IPGeoLocation/core/IpGeoLocationLib.py", line 30, in <module>
    from core.Utils import Utils
  File "/data/data/com.termux/files/home/IPGeoLocation/core/Utils.py", line 35, in <module>
    from core.Logger import Logger
  File "/data/data/com.termux/files/home/IPGeoLocation/core/Logger.py", line 32, in <module>
    from termcolor import colored
ModuleNotFoundError: No module named 'termcolor'

can u fix this ok

**Comment by patricita** [comment]
I'm sorry dude. I unsubscribed a while back, I gave up couldn't figure it
out myself..

**Comment by Lijinlopzs** [comment]
> fix this is please. i want run the ipgeolocation but like this
> ↓
> Traceback (most recent call last):
> File "ipgeolocation.py", line 32, in
> from core.IpGeoLocationLib import IpGeoLocationLib
> File "/data/data/com.termux/files/home/IPGeoLocation/core/IpGeoLocationLib.py", line 30, in
> from core.Utils import Utils
> File "/data/data/com.termux/files/home/IPGeoLocation/core/Utils.py", line 35, in
> from core.Logger import Logger
> File "/data/data/com.termux/files/home/IPGeoLocation/core/Logger.py", line 32, in
> from termcolor import colored
> ModuleNotFoundError: No module named 'termcolor'
> 
> can u fix this ok

Type the below line for install termcolor
"pip install termcolor"

**Comment by ch4iril** [comment]
pip3 install -r requirements.txt --user





if pip3 is missing:

   apt-get install python3-setuptools

   easy_install3 pip

   pip3 install -r requirements.txt

**Comment by Veto4** [comment]
What is the solution to this problem?      ERROR: Could not find a version that satisfies the requirement termcolor (from versions: none)
ERROR: No matching distribution found for termcolor
WARNING: pip is configured with locations that require TLS/SSL, however the ssl module in Python is not available.
Could not fetch URL https://pypi.org/simple/pip/: There was a problem confirming the ssl certificate: HTTPSConnectionPool(host='pypi.org', port=443): Max retries exceeded with url: /simple/pip/ (Caused by SSLError("Can't connect to HTTPS URL because the SSL module is not available.")) - skipping
WARNING: There was an error checking the latest version of pip.

**Comment by ade2000** [comment]
Please run
pip install termcolor

**Comment by sunil2709** [comment]
↓
Traceback (most recent call last):
File "ipgeolocation.py", line 32, in
from core.IpGeoLocationLib import IpGeoLocationLib
File "/data/data/com.termux/files/home/IPGeoLocation/core/IpGeoLocationLib.py", line 30, in
from core.Utils import Utils
File "/data/data/com.termux/files/home/IPGeoLocation/core/Utils.py", line 35, in
from core.Logger import Logger
File "/data/data/com.termux/files/home/IPGeoLocation/core/Logger.py", line 32, in
from termcolor import colored
ModuleNotFoundError: No module named 'termcolor .
 
issue  is maintain of the previous of the commanded.
few customer are still facing the login issue, need to be resolved soon

**Comment by sunil2709** [comment]
still facing the login issue.!!
