### ISSUE TITLE
Traceback (most recent call last):   File "ipgeolocation.py", line 32, in <module>     from core.IpGeoLocationLib import IpGeoLocationLib   File "/root/Downloads/IPGeoLocation-master/core/IpGeoLocationLib.py", line 30, in <module>     from core.Utils import Utils   File "/root/Downloads/IPGeoLocation-master/core/Utils.py", line 33, in <module>     from urllib import request ImportError: cannot import name request

### ISSUE THREAD

**Issue by arunsupersi** [maldevel/IPGeoLocation#31]
not able to run

**Comment by TrollSkull** [comment]
Try this command `pip install request` and then run the script.
Make sure you run the script with `python 3`.
